### ISSUE TITLE
yeast_tavazoie.txt not found execption 

### ISSUE THREAD

**Issue by ShokofehVS** [ShokofehVS/SecBic-CCA#12]
After successful installation of dependencies and installing setup 
While running the scripts (SecBiclib/scripts/secured_cheng_church_yeast.py):

```
Traceback (most recent call last):
  File "SecBiclib/scripts/cheng_church_yeast.py", line 6, in <module>
    data = load_yeast_tavazoie().values
  File "/home/user/.local/lib/python3.8/site-packages/SecBiclib/datasets/load.py", line 27, in load_yeast_tavazoie
    data = np.loadtxt(join(module_dir, 'data', 'yeast_tavazoie', 'yeast_tavazoie.txt'), dtype=np.double)
  File "/home/user/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/user/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/user/.local/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/user/.local/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /home/user/.local/lib/python3.8/site-packages/SecBiclib/datasets/data/yeast_tavazoie/yeast_tavazoie.txt not found
```

**Comment by ShokofehVS** [comment]
#2

**Comment by ibarrond** [comment]
Shouldn't you download the `yeast_tavazoie` dataset and put it somewhere for python to read it?
