### ISSUE TITLE
NumPy Generated Data Failed -- AttributeError: 'float' object has no attribute 'all'

### ISSUE THREAD

**Issue by ShokofehVS** [ShokofehVS/SecBic-CCA#3]
**Description**

While trying to execute `secured_cheng_church_yeast.py` in the scripts over sample NumPy generated data sets fails with: `AttributeError: 'float' object has no attribute 'all'`.

**Data set**

```
num_rows, num_cols = 10,5
n_elements = num_rows*num_cols
np.random.seed(42)                           # Fixed seed for reproducibility
data = np.random.randint(0, 5, size=(num_rows, num_cols))   # Generate data
```

**Full logs:**

```
Traceback (most recent call last):
  File "/home/user/Documents/github/SecBic-CCA/SecBiclib/scripts/secured_cheng_church_yeast.py", line 23, in <module>
    biclustering = secca.run(data)
  File "/home/user/Documents/github/SecBic-CCA/SecBiclib/algorithms/secca.py", line 92, in run
    self._multiple_node_deletion(data, rows, cols, msr_thr, HE, t_enc, t_dec)
  File "/home/user/Documents/github/SecBic-CCA/SecBiclib/algorithms/secca.py", line 141, in _multiple_node_deletion
    stop = True if msr.all() <= msr_thr.all() else False
AttributeError: 'float' object has no attribute 'all'
```

**Comment by ShokofehVS** [comment]
- Decryption of MSR arises this problem since it returns list of MSR instead of single value. 
- Merged with dev_debug branch
